
CREATE TABLE HGTV_INVENTORY (
	LOC_PRI_LBL varchar(25) NOT NULL,
	LOC_PRI_VAL varchar(5) NOT NULL,
	LOC_SEC_LBL varchar(25),
	LOC_SEC_VAL varchar(5),
	UPC varchar(20) NOT NULL,
	QTY INTEGER NOT NULL,
    CREATED_BY VARCHAR(25),
	CREATED_AT TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	UPDATED_AT TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3)
                ON UPDATE CURRENT_TIMESTAMP(3),
	IS_ACTIVE TINYINT(1) DEFAULT TRUE NULL,

	PRIMARY KEY (LOC_PRI_VAL,LOC_SEC_VAL,UPC)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;
