
CREATE TABLE hgtv.INVENTORY (
	LOC_AISLE varchar(5) NOT NULL,
	LOC_SECTION varchar(5) NOT NULL,
	UPC varchar(20) NOT NULL,
	QTY INTEGER NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                ON UPDATE CURRENT_TIMESTAMP,
	IS_ACTIVE BOOL DEFAULT TRUE NULL,
	PRIMARY KEY (LOC_AISLE,LOC_SECTION,UPC)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;
